/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutMe: typeof import('./src/components/AboutMe.vue')['default']
    Bookmark: typeof import('./src/components/Bookmark.vue')['default']
    CalendarWidget: typeof import('./src/components/CalendarWidget.vue')['default']
    ContactWidget: typeof import('./src/components/ContactWidget.vue')['default']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElTag: typeof import('element-plus/es')['ElTag']
    FaceSlider: typeof import('./src/components/FaceSlider.vue')['default']
    FooterNav: typeof import('./src/components/FooterNav.vue')['default']
    ProfileWidget: typeof import('./src/components/ProfileWidget.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RuntimeWidget: typeof import('./src/components/RuntimeWidget.vue')['default']
    SystemWidget: typeof import('./src/components/SystemWidget.vue')['default']
    TimeButton: typeof import('./src/components/TimeButton.vue')['default']
    TopButton: typeof import('./src/components/TopButton.vue')['default']
    WallpaperCard: typeof import('./src/components/WallpaperCard.vue')['default']
    WidgetCard: typeof import('./src/components/WidgetCard.vue')['default']
  }
}
